In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']

In [3]:
myList = [10, 20, 30]

In [4]:
arr = np.array(myList)

In [5]:
arr

array([10, 20, 30])

In [6]:
d = {'a':10, 'b':20, 'c':30}

In [7]:
pd.Series(myList)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data = myList)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
ser1 = pd.Series(data=[1,2,3,4], index=['USA', 'Germany', 'Great Britain', 'Japan'])

In [13]:
ser1

USA              1
Germany          2
Great Britain    3
Japan            4
dtype: int64

In [14]:
ser1["Japan"]

4

In [15]:
ser1[3]

4

In [16]:
ser2 = pd.Series(data=[1,2,3,4], index=['USA', 'Germany', 'Italy', 'Japan'])

In [17]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [18]:
ser1+ser2

Germany          4.0
Great Britain    NaN
Italy            NaN
Japan            8.0
USA              2.0
dtype: float64

In [19]:
np.random.seed(101)
randMat = np.random.randn(5,4)
randMat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [21]:
df = pd.DataFrame(data=randMat, index='A B C D E'.split(), columns='W X Y Z'.split())
dfOriginal = df.copy()
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [24]:
type(df['W'])

pandas.core.series.Series

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [27]:
df['NEW'] = df['W']+df['X']
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [29]:
df1 = df.drop('NEW', axis=1)
df1

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [30]:
df.drop('NEW', axis=1, inplace=True)
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df.drop('A', axis=0)

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [33]:
df.iloc[0,2]

0.9079694464765431

In [34]:
df.loc[['A', 'B'],['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [35]:
df.iloc[[0,1],[0,1]]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [37]:
df.iloc[0:2,0:2]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [39]:
dfBool = df > 0
dfBool

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [40]:
df[dfBool]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [43]:
cond1 = df['W'] > 0
cond2 = df['Y'] > 1
df[cond1 & cond2]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [44]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df.reset_index(inplace=True)
df

level_0 index         W         X         Y         Z
0        0     A  2.706850  0.628133  0.907969  0.503826
1        1     B  0.651118 -0.319318 -0.848077  0.605965
2        2     C -2.018168  0.740122  0.528813 -0.589001
3        3     D  0.188695 -0.758872 -0.933237  0.955057
4        4     E  0.190794  1.978757  2.605967  0.683509

In [47]:
df.drop('index', axis=1, inplace=True)
df

level_0         W         X         Y         Z
0        0  2.706850  0.628133  0.907969  0.503826
1        1  0.651118 -0.319318 -0.848077  0.605965
2        2 -2.018168  0.740122  0.528813 -0.589001
3        3  0.188695 -0.758872 -0.933237  0.955057
4        4  0.190794  1.978757  2.605967  0.683509

In [48]:
df.drop('level_0', axis=1, inplace=True)
df

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [49]:
df['States'] = 'CA NY WY OR CO'.split()
df

W         X         Y         Z States
0  2.706850  0.628133  0.907969  0.503826     CA
1  0.651118 -0.319318 -0.848077  0.605965     NY
2 -2.018168  0.740122  0.528813 -0.589001     WY
3  0.188695 -0.758872 -0.933237  0.955057     OR
4  0.190794  1.978757  2.605967  0.683509     CO

In [50]:
df.set_index('States', inplace=True)
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [53]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [54]:
df = pd.DataFrame({'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [55]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [56]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [57]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [58]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [59]:
df.mean()

A    1.5
B    5.0
C    2.0
dtype: float64

In [60]:
df.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [61]:
df.fillna(0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [62]:
df.fillna(df.mean())

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [63]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [65]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'], 'Pearson':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'], 'Sales':[200,120,340,600,243,350]}
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Pearson': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 600, 243, 350]}

In [66]:
df = pd.DataFrame(data)
df

Company  Pearson  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    600
4      FB     Carl    243
5      FB    Sarah    350

In [67]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     470.0

In [70]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  470.0  183.847763  340.0  405.00  470.0  535.00  600.0

In [71]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  470.000000
      std     75.660426   56.568542  183.847763
      min    243.000000  120.000000  340.000000
      25%    269.750000  140.000000  405.000000
      50%    296.500000  160.000000  470.000000
      75%    323.250000  180.000000  535.000000
      max    350.000000  200.000000  600.000000

In [72]:
df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[444,555,666,444], 'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [73]:
df['col2'].unique()

array([444, 555, 666])

In [74]:
df['col2'].nunique()

3

In [75]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [76]:
def timesTwo(number):
    return number*2

In [77]:
timesTwo(4)

8

In [79]:
df['new']=df['col1'].apply(timesTwo)
df

col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [80]:
df.sort_values('col2')

col1  col2 col3  new
0     1   444  abc    2
3     4   444  xyz    8
1     2   555  def    4
2     3   666  ghi    6

In [81]:
df.sort_values('col2', ascending=False)

col1  col2 col3  new
2     3   666  ghi    6
1     2   555  def    4
0     1   444  abc    2
3     4   444  xyz    8